[tool.isort]
profile = "black"
known_first_party = ["nunchaku"]
line_length = 120

[tool.black]
line-length = 120
target-version = ['py311']

[tool.ruff]
line-length = 120

[project]
dynamic = ["version"]
name = "nunchaku"
dependencies = [
    "diffusers>=0.32.2",
    "transformers",
    "accelerate",
    "sentencepiece",
    "protobuf",
    "huggingface_hub",
    "fastapi",
    "uvloop",
    "boto3",
    "beautifulsoup4",
    "python-dotenv",
]
requires-python = ">=3.10"

[build-system]
requires = [
    "setuptools",
    "torch>=2.5",
    "wheel",
    "ninja",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["nunchaku"]

[tool.doc8]
max-line-length = 120
ignore-path = ["docs/_build"]
ignore = ["D000", "D001"]

[tool.rstcheck]
ignore_directives = ["tabs"]
ignore_messages = ["ERROR/3", "INFO/1"]
